-- PARTE DOIS

-- tb_conta_steam 
INSERT INTO TB_CONTA_STEAM(CODIGO_CONTA_STEAM, CODIGO_EMPRESA, SENHA_EMAIL, TRADE_LINK) VALUES(1,1,'123456','https://steamcommunity.com/');

-- tb_estoque

INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(1,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(2,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(3,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(4,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(5,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(6,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(7,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(8,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(9,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(10,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(11,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(12,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(13,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(14,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(15,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(16,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(17,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(18,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(19,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(20,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(21,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(22,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(23,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(24,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(25,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(26,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(27,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(28,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(29,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(30,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(31,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(32,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(33,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(34,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(35,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(36,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(37,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(38,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(39,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(40,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(41,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(42,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(43,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(44,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(45,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(46,1,true);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(47,1,false);
INSERT INTO TB_ESTOQUE(CODIGO_PRODUTO, CODIGO_CONTA_STEAM, FLAG_QUANTIDADE) VALUES(48,1,true);